### ISSUE TITLE
(med) [Submission form] Scheduling description is unclear

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-course-list#116]
The current text is:

> Indicate the type of activities provided in this resource

Not sure I would describe these as 'activities'. Perhaps something like:

> Indicate how the sessions are scheduled

**Comment by leticiaseixas** [comment]
Agreed with 'activities' not being the best word. 
The primary information in this field being if participants need to be present at a certain time (regardless of whether they are extra activities or teaching sessions), we modified it to:

> Indicate the attendance requirements for this resource.
