### ISSUE TITLE
[Medium] [Confusing wording] -- "Button" should be "link"

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-course-list#128]
Current wording:

> If you wish to add information about a course, training, or certification on web and digital accessibility, please use the following button.  
[Submit a course, training, or certification](https://wai-course-list.netlify.app/course-list/submit-a-resource).

Proposed wording:

> If you wish to add information about a course, training, or certification on web and digital accessibility, please [Submit a course, training, or certification](https://wai-course-list.netlify.app/course-list/submit-a-resource).

We are using a semantic link for the "Submit a course, training, or certification" I am assuming this "looks like a button" and that's why we are calling it as such. That is confusing. I think we could get away with that phrase entirely.

**Comment by leticiaseixas** [comment]
To be consistent with the use of this element on the WAI website, we maintained the link as it is, but the phrase was removed to avoid confusion.
