### ISSUE TITLE
accessibility of courses

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#13]
["Accessibility resources" section](https://deploy-preview-4--wai-course-list.netlify.app/list-of-courses/submit-an-offer#platform) in this draft says:
> **Accessibility resources**
> Describe what accessibility resources are provided in this offer.
>* Audio descriptions
>* Captioning
>* International sign interpretation
>* Other sign language
>* Physical accessibility
>* Real-time captioning
>* Transcripts
>* Other
<hr>

Thank you for including this. It is important. This is a great start! I do think it needs more consideration. For example, what if some of these are not applicable? What is “physical accessibility”? This seems geared towards multimedia. What about the rest of the course?

_Here is a **rough**, **incomplete**, **unpolished** idea of a possible approach._

**Accessibility Support**

Indicate what accessibility support is provided. Include details in the text box.

* All content meets  [Web Content Accessibility Guidelines (WCAG) Overview](https://www.w3.org/WAI/standards-guidelines/wcag/) -- Level A, AA, or AAA
* Content meets relevant good practice in [How to Make Your Presentations Accessible to All]( https://www.w3.org/WAI/teach-advocate/accessible-presentations/).
* Audio and video content meets the good practice in [Audio Content and Video Content](https://www.w3.org/WAI/media/av/av-content/)
* [Description of visual information](https://www.w3.org/WAI/media/av/description/) -- integrated description, audio description, or text description
* [Captions ](https://www.w3.org/WAI/media/av/captions/)(also called intralingual subtitles), live captions (also called real-time or CART)
* [Transcripts ](https://www.w3.org/WAI/media/av/transcripts/)-- basic transcripts, descriptive transcripts, interactive transcripts
* [Sign language](https://www.w3.org/WAI/media/av/sign-languages/) interpretation -- International Sign, or other language
* [Media player accessibility](https://www.w3.org/WAI/media/av/player/)
* Other

**Comment by bakkenb** [comment]
+1 to the approach outlined by Shawn above for the Accessibility section. I like the links too because if they have not thought about some of those, they will now know where to go to get the info on what they mean and how to implement.

**Comment by eoncins** [comment]
+1 to the approach proposed by Shawn because it includes the terms used in different regions.
Agree with Shawn what is "Physical accessibility"? Also agree that the accessibility resources are based on media accessibility services, how about other aspects such as "alt-text", "colour contrast", "focus order"...?
I would also include "Easy-to-understand, Plain Language, Easy-to-read".
