### ISSUE TITLE
[High] Live region with shown courses interrupts navigation through combo box lists

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-course-list#131]
to replicate using NVDA on windows

* Focus one of the combo boxes for country or language
* Ensure focus mode is enable by pressing Insert+space until you hear a piano-like sound
* Press the down arrow key
* First thing read is the updated live region results. Second thing is the currently selected list item.

This hinders SR users efficiency quite significantly. You need to wait for the live region message to be spoken until you hear the currently selected item.

I would suggest the live region only updates when the combo box gets closed by pressing Enter or when the user dismisses the combo box by moving away from it.

**Comment by leticiaseixas** [comment]
NVDA [seems to ignore events associated with pressing Enter in select boxes](https://github.com/nvaccess/nvda/issues/7898).
To avoid over-complicating this interaction, the aria-live is now turned off when focusing these fields, and a status message containing the total number of search results has been added - focusable right after each field.
