### ISSUE TITLE
expand/collapse in sections of submission form

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-course-list#17]
not sure if/why this would be needed. if someone is completing the form they will need all sections. -?-

**Comment by bakkenb** [comment]
+1 to no expand/collapse here.

**Comment by shawna-slh** [comment]
I also don't see purpose of Expand-Collapse for "About You" and "About the Offer."

I can see use for it under "WAI Curricula module", especially when there are 4 very different ones. I don't feel strongly either way.

**Comment by leticiaseixas** [comment]
We removed the expand/collapse in sections of the form. 

We decided to keep it under the "WAI Curricula module", as it has the potential to grow into a long list.
