### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-course-list#19]
I ma not sure it is clear what the duration refers to. Is it meant to indicate that the class will be available for 6 months or a year or so - OR - is meant to say this class will take you 3 hours or 3 weeks or 3 months to complete? Maybe it needs two parts:
1. length of time to complete the course
2. Duration of time the course will be available

**Comment by bakkenb** [comment]
This is a really good question. My initial understanding of the section was the length of time assumed it would take someone to complete the course. This is needed and helpful. But agree with Sharron that there is more to ask here.

If the course itself is not available indefinitely, like, you only have 3 months to finish once you enroll and receive access, then that would be another area of indication in the About this Offer section.

**Comment by eoncins** [comment]
Agree that this is a relevant question. To me the time duration is the lenght of the course in itself. As @bakkenb mentions if this is a self paced course then it should be indicated.

**Comment by leticiaseixas** [comment]
- We modified this attribute to "Length" and provided some clearer information on what is intended to be filled in this option.
- We also included a new attribute "Availability" to providers indicate the duration of time the course will be available. In the case this is a self-paced course, the end date is not required.
