### ISSUE TITLE
Excessive additional information text

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-course-list#20]
For consideration.

Many of the fields include variations of: 'Indicate the ...'. For example, 'Duration (Required), Indicate the duration of this offer'. Many of these may be unnecessary and don't really add much value. Some examples that I think could be removed:

* Type - although the label could be changed to 'Type of offer' (or course if the word is changed!)
* Audience
* Level
* Prerequisites and Topics - could be changed to just 'For example, ...'
* Language
* Country
* Format
* Learning
* Platform - could be 'e-learning platform'
* Duration
* Cost

**Comment by bakkenb** [comment]
Kevin brings up a good point. If there is a field where they are supposed to put a link in that brings people to a page with more information about the course, then maybe some of this other information is not needed and should be covered in the course webpage. That way it will also have less chance of having "old" info on our list that was changed by the provider and never updated with us.

**Comment by leticiaseixas** [comment]
> For consideration.
> 
> Many of the fields include variations of: 'Indicate the ...'. For example, 'Duration (Required), Indicate the duration of this offer'. Many of these may be unnecessary and don't really add much value. Some examples that I think could be removed:
> 
> * Type - although the label could be changed to 'Type of offer' (or course if the word is changed!)
> * Audience
> * Level
> * Prerequisites and Topics - could be changed to just 'For example, ...'
> * Language
> * Country
> * Format
> * Learning
> * Platform - could be 'e-learning platform'
> * Duration
> * Cost



We removed the additional information in cases they were not providing any additional information:

- Type (now Type of resource) - removed
- Audience - removed
- Level - we believe that is important to emphasize that level is related to digital accessibility proficiency required
- Prerequisites and Topics - _could be changed to just 'For example, ...'_ - removed
- Language - we believe that this additional information is important to emphasize that it is possible to add one or more languages
- Country - same as language
- Format - removed
- Learning (Activities) - yet to be discussed in #30 
- Platform - _could be 'e-learning platform'_ - We received some suggestions on how the course can be provided on other platforms, not just on e-learning. Also, some previews comments on this attribute indicated that just providing its name was not very clear. For now, we modified it to "If applicable, indicate on which platform this course, training, or certification is provided.". Just a side note on this, we believe that an example could be useful, but we decided not to include it to not endorse any particular platform. Do you think that this information could be improved? If so, do you have any suggestions?
- Duration (Length) - we believe this additional information is also needed to better understand this field, as well as it now provides some examples to better inform users.
- Cost - removed
