### ISSUE TITLE
[list itself] to update info, right box, disclaimer

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#201]
preview: https://deploy-preview-191--wai-course-list.netlify.app/courses/list/#disclaimer

In the box on the right is:
> If you wish to update any information or remove a course included in this list, please contact us via e-mail to the editors group list: [group-wai-list-courses@w3.org](mailto:group-wai-list-courses@w3.org?subject=Update%20course)

I don't think we want to give that so much prominence. Options:
1. add "or update" to the button "Submit a course, training, or certification"  -> "Submit or update a course, training, or certification". Then hopefully they easily see there to send email. Maybe make that more prominent on that page.
2. Move it under the "Submit a course, training, or certification" button, and make it more succinct, e.g.: "If you want to update information in the list or delete a course, please send e-mail to [group-wai-list-courses@w3.org](mailto:group-wai-list-courses@w3.org)"

---

I see that the [draft Eval Tools List update](https://master--wai-evaluation-tools-list.netlify.app/list-of-evaluation-tools/) has the short disclaimer wording and link in that area -- box on the right.

That seems like a good place for the short disclaimer wording, so it is more prominent.

**Comment by leticiaseixas** [comment]
1. added "or update" to the button "Submit a course, training, or certification" -> "Submit or update a course, training, or certification". 
	- probably the best option, as this form is also intended for update courses, therefore will soon enable editing entries.
2. made email to update info more prominent on the submission form
3. moved the short disclaimer wording and link in the box on the right

**Comment by leticiaseixas** [comment]
updated list preview: [https://deploy-preview-221--wai-course-list.netlify.app/courses/list/](https://deploy-preview-221--wai-course-list.netlify.app/courses/list/)
updated form preview: [https://deploy-preview-221--wai-course-list.netlify.app/courses/submission/](https://deploy-preview-221--wai-course-list.netlify.app/courses/submission/)

**Comment by shawna-slh** [comment]
> made email to update info more prominent on the submission form

humm - except now "If you want to update information in the list or delete a course" is confusing because there is no course list to update and delete from. :-)

Maybe best not to have that section at all until the list is published?
