### ISSUE TITLE
Edits for introductory paragraph on the list of courses

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-course-list#21]
For consideration:

> The List of Courses provides information about courses, training, and certification on web accessibility from different providers, so that people can make informed decisions when they choose an offer. This page provides a list of courses that you can filter to find ones that match your needs.

**Comment by sharronrush** [comment]
I think the Note is too easy to ignore and might usefully be brought into the main paragraph. Perhaps something like this:

This List of Courses provides information about courses, training, and certification on web accessibility from different providers. It is meant to help you make informed decisions to choose a resource. The page allows you to filter submissions to find ones that match your specific interest and need. Please note that the list items are provider-submitted, not W3C-endorsed. See the full disclaimer for more information about vendor-submitted content.

**Comment by bakkenb** [comment]
When first reading the intro paragraph I was looking for "something" that indicated very clearly that they were submitted by others and this is just a way to search various criteria of what is submitted. 

I agree with the simplification of the intros by Kevin and Sharron above, especially the addition of the last part of Sharron's example. I feel strongly that it has to be clearly stated.

**Comment by eoncins** [comment]
+1 to simplification.
Also, it is confusing to use "List of Accessibility Courses: Education, training, and certification" and then "submit an offer"

**Comment by vmmiller** [comment]
> For consideration:
> 
> > The List of Courses provides information about courses, training, and certification on web accessibility from different providers, so that people can make informed decisions when they choose an offer. This page provides a list of courses that you can filter to find ones that match your needs.

1. Suggest to modify slightly:  "when they select an offer". 
2. Add a disclaimer sentence see @sharronrush  version above.

**Comment by leticiaseixas** [comment]
- Updated according to @sharronrush suggestion
- Changed the button to "Submit a course, training, or certification", according to @eoncins comment.
