### ISSUE TITLE
Unclear link text for updating existing resource

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-course-list#23]
> This form allows you to provide information about courses, training, and certification on web accessibility. If you wish to update an existing resource, please, upload the file provided when first submiting through this [link](https://619686585c106900071bf884--wai-course-list.netlify.app/list-of-courses/submit-an-offer#)

Suggested edit:

> This form allows you to provide information about courses, training, and certification on web accessibility. For existing resources, please [update the existing resource file](https://619686585c106900071bf884--wai-course-list.netlify.app/list-of-courses/submit-an-offer#)

**Comment by leticiaseixas** [comment]
Fixed!
