### ISSUE TITLE
Fix breadcrumb / sidebar navigation on full site navigation

### ISSUE THREAD

**Issue by leticiaseixas** [w3c/wai-course-list#247]

**Comment by shawna-slh** [comment]
Hi @leticiaseixas 

The breadcrumb is generated from the navigation.yml file. This might do it: https://github.com/w3c/wai-website-data/pull/89/files

Hopefully you can test that locally.

I'm not sure if there will be any hiccups because the list page doesn't have secondary navigation? We should plan to test that well before publishing.

**Comment by shawna-slh** [comment]
As shown in https://github.com/w3c/wai-website-data/pull/89/files , current proposal is to put the Course List under:
Accessibility Fundamentals > Courses

Here's a [draft new Digital Accessibility Courses Overview page](https://deploy-preview-74--wai-fundamentals-overview.netlify.app/courses/)

Input welcome: [PR](https://github.com/w3c/wai-fundamentals-overview/blob/when-course-list-publish/content/courses.md)

**Comment by shawna-slh** [comment]
hey @SteveALee . I see "Course List: Getting an Accessibility Fundamentals nav side bar" on your To Do list. I think we do ***not*** want that.

I think we want the full page width for the lists -- since the filters take up a bunch of space. @leticiaseixas can you confirm?

**Comment by leticiaseixas** [comment]
Yes, I confirm. We do **_not_** want the secondary navigation side bar - and that is our current issue.

**Comment by SteveALee** [comment]
@shawna-slh sorry badly worded - should be "remove"

**Comment by shawna-slh** [comment]
@leticiaseixas In case it helps -- here are a couple of pages that do not have the secondary/left nav... although the also don't use full width :-/
* https://www.w3.org/WAI/resources/
* https://www.w3.org/WAI/translations/

**Comment by SteveALee** [comment]
The side nav is now not showing for the two pages. I added a `page.no-sidenav` value to the theme to support this . ie 

ie this in page yaml:

```
no-sidenav: true
```

**Comment by shawna-slh** [comment]
> I added a page.no-sidenav value to the theme to support this

thanks, @SteveALee ! and did you document it where we can find it when we want it in the future? :-)

**Comment by SteveALee** [comment]
@shawna-slh see https://wai-website-theme.netlify.app/technical/navigation/#hide-side-navigation-menu-from-a-page

Did you mean to close as breadcrumbs was not specifically addressed AFAICS
