### ISSUE TITLE
[!!] Dynamic heading confusing

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-course-list#278]
Apologies for just bringing this up, but the "Showing [number] courses" heading is confusing and disruptive -- when using a screen reader and visually. If you want to alert users that their list of choices has updated, this can still be part of text below the heading and tied to an alert, but I don't think we should set a pattern of making headings dynamic alerts. 

Also, when bringing up a list of headings with a screen reader, it would be much more informative to see/hear "Course List" than "Showing 20 courses". For repeat visitors, it will also help to know the headings of most interest (e.g., jumping to "Filters" then "Course list") and cognitively it will be less jarring than an ever-changing heading.

cc: @shawna-slh - to see if she agrees

**Comment by shawna-slh** [comment]
> cc: @shawna-slh - to see if she agrees

Let's ask some screen reader users. @Sylvie42 ? others?

**Comment by Sylvie42** [comment]
Hello @MicheleAWilliams-A11y and @shawna-slh,

I just tested selecting new courses by checking a checkbox. There is an alert indicating that 3 courses out of 5 are shown. This is good information.

Then, when browsing from heading to heading, I don't find it confusing to hear / read : "Showing 3 from 5 courses". This information seems to me helpful as you know that you see 3 courses and that there are 2 other remaining. 

But what is confusing is that there are 5 courses and you don't know how to see the two remaining courses. Do you have to modify filters? 

At last, there is a heading issue: you have heading 2 "Showing 3 from 5 courses", then heading 4 "Current filter criteria", (this should be a heading 3?)

**Comment by leticiaseixas** [comment]
@Sylvie42 Would it be clearer if we changed the mentioned text to something like "Showing X filtered courses out of a total of X courses"?

**Comment by daniel-montalvo** [comment]
Thanks @MicheleAWilliams-A11y @Sylvie42 @shawna-slh and @leticiaseixas for bringing this to my attention.

I wonder if the phrase "Current filter criteria" should even be a heading. If so, it should definitely follow the heading hierarchy and be an h3.

I'd say the heading "showing [number] courses" should be kept even if it changes as filters are applied.

> @Sylvie42 Would it be clearer if we changed the mentioned text to something like "Showing X filtered courses out of a total of X courses"?

Even shorter and more succinct, "showing 3 out of 5 courses"

If you want to get to the other two that are hidden, you have to clear filters. To me that is a clear pattern in itself and does not require more explanation.

**Comment by Sylvie42** [comment]
Hello,

I agree with @daniel-montalvo.

Best

Sylvie

**Comment by leticiaseixas** [comment]
"Current filter criteria" is not a heading anymore.
