### ISSUE TITLE
Skip links / Access keys

### ISSUE THREAD

**Issue by leticiaseixas** [w3c/wai-course-list#283]
Previous versions of the Course List included two skip links and two accesskeys to jump to results (r) and jump to filters (f) (see https://deploy-preview-208--wai-course-list.netlify.app/courses/list/). These followed the same behavior as the "skip to content" standard feature used on the minimal header. However, with the full header, this interaction does not work so well:

- The "skip to content" link in the full header is a link integrated in the header. It does not seem right to include other links in there, as this would be inconsistent through the WAI website.
- Using the same behavior as the minimal header, i.e., as it was implemented before, means that the "skip to content" would have a different behavior than the others skip links, and this would also be inconsistent.

Considering we do not have a filter button, this would be a good addition for people to navigate through filters and results. So, two questions come to mind: 
- Should we be using access keys at all? I don't think this is used anywhere else on the WAI website.
- If so, what would be the best way to integrate this feature into this resource, considering the use of the full header?

@shawna-slh @SteveALee  Any thoughts on this?

**Comment by SteveALee** [comment]
Thanks for a really clear explanation. I've a few quick thoughts.

- changing the main site fixed skip links link to a dynamic button like the standalone resource one might work
- I'm not sure multiple skip links to different areas is a good idea. It certainly not a pattern I've seen often. It adds extra hidden tabstops. If only browsers offered a list of headings like screenbreaders do.
- access keys used to be a pain to use and may still be if browsers still use different key modifiers to activate them. Also there's no standard way for users to discover them. Browser provide no view, though some google suite apps do have a help page triggered by the ? Key.

So im leaning towards a single skip link and no access keys. If jumps to particular areas of the page are useful perhaps just explicit links at the top/bottom of the content might be suitable, at the risk of clutter? Ie like a ToC :)

**Comment by daniel-montalvo** [comment]
Thanks @leticiaseixas for this background. It is really helpful.

+1 to only one "Skip to main content" link and no access keys as @SteveALee suggests.

**Comment by leticiaseixas** [comment]
+1 to only one "Skip to main content" link and no access keys

 I'd say consider this closed if there's no other objections.
