### ISSUE TITLE
[ED-LO-MED] Important Disclaimer in DOM order

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#285]
Currently is:
...
* h2> Filters
* h2> Important Disclaimer
* h2> Showing 5 courses
...

I think ideally the "Important Disclaimer" would be near the end, rather than interrupting the flow from the filters to the results. (since we already have near the beginning  "...W3C does not endorse specific courses. See [Important Disclaimer](https://@@)."

**Comment by leticiaseixas** [comment]
Hi Shawn,

I understand and agree with your point. However, I am concerned about the visual order being different from the DOM order (screen reader structure). Shouldn't we then discuss about moving the "Important Disclaimer"?

**Comment by shawna-slh** [comment]
Hi @leticiaseixas
Sure. I see it's different in the [Eval Tools List prototype](https://master--wai-evaluation-tools-list.netlify.app/list-of-evaluation-tools/#disclaimer). Could you work with Vera on a proposal for consistent placement, visual design, and wording among the new tools? :-)

**Comment by leticiaseixas** [comment]
Disclaimer box moved to the bottom of the page, after the results listing.
