### ISSUE TITLE
[ED-LO-MED] clearer dates

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#286]
I think it's not easy to figure out what these dates are:
>This information was last updated on 20 April 2022.
>The content of this resource was last updated on 1 April 2022.

Proposal:
* For the date the course was updated, use a bold label like the other info about the course itself:

> **Content updated:** 1 April 2022

* For the date the listing was updated, put it at the end and in italics:
> _This listing was updated 20 April 2022._

**Comment by bakkenb** [comment]
I completely agree with this change and the use of bold for "content updated" and styled like the other listing topics with a colon. This is much more clear what the two dates are meaning.
