### ISSUE TITLE
[ED-LO] title

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#287]
> Course List of Digital Accessibility Education, Training, and Certification

APOLOGIES that I'm bringing this up again. Feel free to close it without any more consideration.

It's just that this title wording keeps nagging at me as awkward and improper. I don't have my grammar hat on to define why.

I think either of these options would be smoother:

1. Course List &mdash; Digital Accessibility Education, Training, and Certification
2. Course List: Digital Accessibility Education, Training, and Certification

**Comment by leticiaseixas** [comment]
+1
Changed to: Course List - Digital Accessibility Education, Training, and Certification
