### ISSUE TITLE
Accessibility support options

### ISSUE THREAD

**Issue by leticiaseixas** [w3c/wai-course-list#29]
(previous #13 #16)

Combined previous input with relevant information in [How to Make Your Presentations Accessible to All](https://www.w3.org/WAI/teach-advocate/accessible-presentations/) 

Currently:

**Accessibility support**
Indicate what relevant accessibility support is provided (see guidance on How to Make Your Presentations Accessible to All). Include details in the text box.

- **Material**
   - Material provided ahead of time, if requested
   - Handouts, slides, and other material in accessible formats - for example, large print or braille
   - Handouts, slides, and other electronic material is accessible - all content meet [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/), at least Level AA
   - Media fully accessible - including audio and video used in sessions, and recordings of sessions provided afterwards - see [Making Audio and Video Media Accessible](https://www.w3.org/WAI/media/av/)

- **Sessions**
   - Facility and area accessible to participants - for example, the building entrance, meeting room, presentation stage, and bathrooms are accessible
   - [Assistive listening devices](https://www.w3.org/WAI/teach-advocate/accessible-presentations/#ald) (ALD), [interpreters](https://www.w3.org/WAI/teach-advocate/accessible-presentations/#terps), and [captioners](https://www.w3.org/WAI/teach-advocate/accessible-presentations/#captions), provided as needed
   - [Captions](https://www.w3.org/WAI/media/av/captions/) and/or [transcripts](https://www.w3.org/WAI/media/av/transcripts/) for audio
   - [Description of visual information](https://www.w3.org/WAI/media/av/description/) - integrated description, audio description, or text description
   - Pre-session technology check, if requested - dedicated time to participants set up any relevant technology, or additional settings

- **Slides and Projected Material**
   - Text and important visuals big enough to be read even from the back of the room
   - Easy-to-read font face
   - Sufficient contrast between colors (“luminance contrast”) - see [Understanding contrast guidance](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced) and [contrast evaluation tools](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced#resources)
   - Reduced use of motion or animations - see [Understanding Animation from Interactions guidance](https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions.html)

**Comment by shawna-slh** [comment]
quick notes for now since I can't be in the meeting:
* In thinking about what to include here or not, consider difference between wanting to educate course providers, versus what potential students and procurers will want to know about the course beforehand (and potentially filter on).
* There may also be other relevant issues, e.g., accessibility of LMS ? See also [Accessibility of Remote Meetings](https://www.w3.org/TR/remote-meetings/)
* Do we have any thoughts on handling "not applicable"

**Comment by iadawn** [comment]
I might suggest:

* 'Slides and handouts' instead of 'Materials'
* 'Slide content' instead of 'Slides and Projected Material'

Regarding 'not applicable' I think that may only be relevant if there is some scoring based on the number of things checked?

**Comment by leticiaseixas** [comment]
@shawna-slh, this field only concerns "applicable" supports, as mentioned in the explanation paragraph.

@shawna-slh, concerning accessibility of LMS, we believe the "Platform" field, providing information about used systems, also helps people have more information about the accessibility of tools used in each resource. We are not sure if the accessibility of these tools is in the scope of this resource for now.

Considering the latest feedback, our current proposal is: 

### Accessibility support
If applicable, indicate what accessibility support is provided (see guidance on [How to Make Your Presentations Accessible to All](https://www.w3.org/WAI/teach-advocate/accessible-presentations/)). Include details in the text box.

**General accessibility**
- [ ] Material provided ahead of time, if requested
- [ ] Pre-session technology check, if requested - dedicated time to participants set up any relevant technology or additional settings

**Digital accessibility**
- [ ] Handouts, slides, and other electronic material is accessible - all content meet [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/), at least Level AA, including:
   - [ ] [Captions](https://www.w3.org/WAI/media/av/captions/) and/or [transcripts](https://www.w3.org/WAI/media/av/transcripts/) for audio
   - [ ] Text and important visuals big enough to be read
   - [ ] Easy-to-read font face
   - [ ] Sufficient contrast between colors (“luminance contrast”) - see [Understanding contrast guidance](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced) and [Contrast evaluation tools](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced#resources)
   - [ ] Reduced use of motion or animations - see [Understanding Animation from Interactions guidance](https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions.html)
   - [ ] [Description of visual information](https://www.w3.org/WAI/media/av/description/) - integrated description, audio description, or text description

**Non-digital accessibility**
- [ ] Facility and area accessible to participants - for example, the building entrance, meeting room, presentation stage, and bathrooms are accessible
- [ ] [Assistive listening devices](https://deploy-preview-4--wai-course-list.netlify.app/course-list/submit-a-resource#:~:text=Assistive%20listening%20devices) (ALD), [interpreters](https://www.w3.org/WAI/teach-advocate/accessible-presentations/#terps), and [captioners](https://www.w3.org/WAI/teach-advocate/accessible-presentations/#captions), provided as needed
- [ ] Handouts, slides, and other material in accessible formats, including:
   - [ ] Text and important visuals big enough to be read even from the back of the room
   - [ ] Easy-to-read font face
   - [ ] Sufficient contrast between colors (“luminance contrast”) - see [Understanding contrast guidance](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced) and [contrast evaluation tools](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced#resources)
   - [ ] [Description of visual information](https://www.w3.org/WAI/media/av/description/) - audio description and text description

Additional accessibility support:

**Comment by leticiaseixas** [comment]
Considering the latest feedback, our current proposal is: 

### Accessibility support
If applicable, indicate what accessibility support is provided (see guidance on [How to Make Your Presentations Accessible to All](https://www.w3.org/WAI/teach-advocate/accessible-presentations/)). Include details in the text box.

#### General accessibility
- [ ] Material provided ahead of time, if requested
- [ ] Pre-session technology check, if requested - dedicated time to participants set up any relevant technology or additional settings

#### Digital accessibility
Handouts, slides, and other electronic material is accessible, including:
- [ ] [Captions](https://www.w3.org/WAI/media/av/captions/) and/or [transcripts](https://www.w3.org/WAI/media/av/transcripts/) for audio
- [ ] Easy-to-read font face
- [ ] Text and important visuals big enough to be read
- [ ] Sufficient contrast between colors (“luminance contrast”) - see [Understanding contrast guidance](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced) and [Contrast evaluation tools](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced#resources)
- [ ] Reduced use of motion or animations - see [Understanding Animation from Interactions guidance](https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions.html)
- [ ] [Description of visual information](https://www.w3.org/WAI/media/av/description/) - integrated description, audio description, or text description
- [ ] All content meet [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/), at least Level AA

#### Non-digital accessibility
- [ ] Facility and area accessible to participants - for example, the building entrance, meeting room, presentation stage, and bathrooms are accessible
- [ ] [Assistive listening devices](https://deploy-preview-4--wai-course-list.netlify.app/course-list/submit-a-resource#:~:text=Assistive%20listening%20devices) (ALD), [interpreters](https://www.w3.org/WAI/teach-advocate/accessible-presentations/#terps), and [captioners](https://www.w3.org/WAI/teach-advocate/accessible-presentations/#captions), provided as needed

Handouts, slides, and other material in accessible formats, including:
- [ ] Easy-to-read font face
- [ ] Text and important visuals big enough to be read even from the back of the room
- [ ] Sufficient contrast between colors (“luminance contrast”) - see [Understanding contrast guidance](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced) and [contrast evaluation tools](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced#resources)
- [ ] [Description of visual information](https://www.w3.org/WAI/media/av/description/) - audio description and text description

Additional accessibility support:
