### ISSUE TITLE
[medium-high] individual wanting training vs. customized training for an organization

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#302]
Hey @leticiaseixas In reviewing the submissions, I had a few thoughts, and re-looked at the [requirements](https://www.w3.org/WAI/EO/wiki/WAI_Curricula/List_of_Courses). Two very different scenarios:
1. Individuals - I want to take a course
2. Organizations - I want to hire a trainer/company to provide training for staff in my organization (likely customized to my situation)

Now, looking at the [current UI](https://deploy-preview-248--wai-course-list.netlify.app/courses/list/), I can't really figure out how to filter for that. 

Am I missing something, or do we need to reconsider Filters?

**Comment by leticiaseixas** [comment]
The current proposal is to add an extra field to the submission form, which will be included as a new filter in the course list.
Possible suggestions:

1. Who can take this? (Choose as many as apply) (Not required)
[ ] Individuals
[ ]Organizations	

2. Registration type (Choose as many as apply) (Not required)
[ ] Individual
[ ] Organizational
[ ] Groups

**Comment by AndrewArch** [comment]
The thought I had was to offer the choices somewhere of
[] Public course
[] In-house course
But your suggestions would work fine @leticiaseixas

**Comment by leticiaseixas** [comment]
Proposal preview available at:
- [Course list preview](https://deploy-preview-320--wai-course-list.netlify.app/courses/list/)
- [Submission form preview](https://deploy-preview-320--wai-course-list.netlify.app/courses/submission/)
