### ISSUE TITLE
[low-medium] order of Type of resource

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#303]
Based on the current submissions, I think we should revisit at least the order of: 
> Type of resource
> [ ] Graduate program (0)
> [ ] Undergraduate program (0)
> [ ] Professional certification (2)
> [ ] Training (14)
> [ ] Other (0)

Seems like Training should be first.

Also, do we want to keep separate for Graduate program and Undergraduate program? Since there will be very few, maybe the Filter is combined (even of the data is separate in the details listing)

see also: [individual wanting training vs. customized training for an organization #302](https://github.com/w3c/wai-course-list/issues/302) &mdash; maybe these are addressed together?

**Comment by leticiaseixas** [comment]
Type of resource updated to have Training first:

[ ] Training (14)
[ ] Graduate program (0)
[ ] Undergraduate program (0)
[ ] Professional certification (2)
[ ] Other (0)

- still to be addressed: Combine Graduate program and Undergraduate program
- maybe it is better to **not** address #302 together to better distinguish those issues
