### ISSUE TITLE
[medium] promote W3Cx accessibility course

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#317]
Unless there are concerns, I think we want to "highlight" the [WAI course](https://www.w3.org/WAI/fundamentals/foundations-course/). I'm thinking in addition to including it in the list with others, that we have near the top:
* at least a sentence and link in the intro text area
<br>_or,_
* maybe a box right of h1 and above disclaimer blurb - with an image and short blurb?

**Comment by shawna-slh** [comment]
Hi @leticiaseixas -- I added this to the EOWG agenda for 2 Sept. Any chance you could give some thought to options, and possibly even provide preview(s)?

**Comment by leticiaseixas** [comment]
- sentence and link in the intro text area: [Preview](https://deploy-preview-325--wai-course-list.netlify.app/courses/list/)

- box right of h1 and above disclaimer blurb - with an image and short blurb: [Preview](https://deploy-preview-324--wai-course-list.netlify.app/courses/list/)

_text and images for viewing purposes only - are still to be further addressed_

**Comment by daniel-montalvo** [comment]
Thanks much @leticiaseixas 


`Just noted this code snippet right before the link to the EDX/WAI course


```html
        <img src="/content-images/wai-course-list/w3c.png" alt="alternative text" class=" tiny">
```


We may want to mark this image as decorative if we go for this option.

**Comment by shawna-slh** [comment]
> We may want to mark this image as decorative if we go for this option.

I think alt="W3C logo"

**Comment by shawna-slh** [comment]
resolved with https://github.com/w3c/wai-course-list/pull/325#issuecomment-1238715900
