### ISSUE TITLE
draft note placement - OK to leave for a couple days until we announce next week

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#332]
Hi @leticiaseixas I added the draft note text in the frontmatter and it's not positioned correctly. Options:
1. Just leave it. It stands out better and makes it more clear that it's a draft page :-)
2. move it
2.1. delete from frontmatter: ```doc-note-message: <p><strong>Please do not share links</strong> to this draft page yet. We plan to announce it in September 2022. To get notified when it is ready to share, subscribe to <a href="https://www.w3.org/WAI/news/subscribe/">Get WAI News</a>.</p>```
2.2. add either  before ```</header>``` **_or_** under ```<div class="header-left">``` this:

```

<section class="doc-note-box">
  <p><strong>Please do not share links</strong> to this draft page yet. We plan to announce it in September 2022. To get notified when it is ready to share, subscribe to <a href="https://www.w3.org/WAI/news/subscribe/">Get WAI News</a>.</p>
</section>

```

Because we plan to officially publish and announce early next week, I'm fine with #1. Also OK with #2. if you prefer.

**Comment by leticiaseixas** [comment]
draft note removed - as the list is now published.
