### ISSUE TITLE
[high-med] bug in details?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#342]
![image](https://user-images.githubusercontent.com/6991814/190295029-58fb3ac1-1e84-4864-a834-228def6dee1d.png)

brief ALT: some data seems to be missing

**Comment by leticiaseixas** [comment]
Thanks for spotting that, @shawna-slh- It was an inconsistency between the submission files and how the information is read afterwards - in the case of non-mandatory and unfilled fields. It's already fixed.
