### ISSUE TITLE
How do I see the list of courses?

### ISSUE THREAD

**Issue by mgifford** [w3c/wai-course-list#359]
The link in the project page went to a [wiki](https://www.w3.org/WAI/EO/wiki/WAI_Curricula/List_of_Courses). 

I was expecting to find something basic like https://github.com/accessibility/a11y-courses

or for that matter just a GitHub Pages.

**Comment by carlosapaduarte** [comment]
@mgifford the course list can be found at https://www.w3.org/WAI/courses/list/

Btw, what project page are you referring to?

**Comment by carlosapaduarte** [comment]
Of course! We'll update it.

**Comment by mgifford** [comment]
Thanks @carlosapaduarte

**Comment by shawna-slh** [comment]
updated https://github.com/w3c/wai-course-list/blob/master/README.md

Thanks @leticiaseixas @carlosapaduarte  @mgifford
