### ISSUE TITLE
Submission failure page missing text

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-course-list#393]
`strings.contact_email_list_courses` is used as the link text on failure.md but does not appear to be defined

**Comment by shawna-slh** [comment]
Is that the group lists? They are:

group-wai-list-courses@w3.org

group-wai-list-authoring-tools@w3.org

**Comment by leticiaseixas** [comment]
Hi @SteveALee,

it looks like it is defined at [strings.yml](https://github.com/w3c/wai-course-list/blob/7d03186fd38e01a0822102ae513e8066c40fc4cc/_data/wai-course-list/strings.yml#L13)

It is also displaying correctly at the failure page: [https://www.w3.org/WAI/courses/submission/failure](https://www.w3.org/WAI/courses/submission/failure)

Is there anything else I missed?
