### ISSUE TITLE
Submission form not working

### ISSUE THREAD

**Issue by leticiaseixas** [w3c/wai-course-list#415]
Hi all @SteveALee @shawna-slh, the submission form is always redirecting to the failure page.
From my side, the json file is being generated correctly - and no modifications were made since the last submission (Dec 30), i.e., the last known date the form was working.
I do not have access to debug the live version or to check if there are error logs on netlify.
Any thoughts on why this is happening?

**Comment by SteveALee** [comment]
My guess is it's failing in the git hub action that creates the pull request. This is called from the Netlify Function invoked for the form action.

I had a PAC expire and if that was being used by the action it will be broke.

If so @michael-n-cooper should be able to generate a new PAC and configure it.

I no longer have suitable access.

**Comment by shawna-slh** [comment]
@iadawn This is probably the same issue with the Authoring Tools list failing. Let me know if there's something for me to do...

**Comment by leticiaseixas** [comment]
Submission form has been fixed. This issue can now be closed.
