### ISSUE TITLE
2 not Graduate / Undergraduate programs

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-course-list#479]
In https://www.w3.org/WAI/courses/list/

I select the Filter "Graduate / Undergraduate program (2)"

I was looking for university (or college, etc) courses.

Neither of the two are.

I don't think they should be categorized as such.

(@iadawn example of things that need to be checked)

**Comment by leticiaseixas** [comment]
Thanks for pointing this out @shawna-slh. 
The issue was originated from the merge of "Graduate" and "Undergraduate" program filters in #303, where some entries were temporarily edited for testing and inadvertently went live.
It is now correct.
